library(boot) 
library(car)
library(QuantPsyc)
library(lmtest)
library(sandwich)
library(vars)
library(nortest)
library(MASS)

setwd("E:\\finder\\work\\R\\kaggle\\HousePrices")
data<- read.csv("E:\\finder\\work\\R\\kaggle\\HousePrices\\train.csv")
str(data)
data$OverallQual = as.factor(data$OverallQual)
data$OverallCond= as.factor(data$OverallCond)
data$YearBuilt= as.integer(data$YearBuilt)
data$BsmtFullBath= as.factor(data$BsmtFullBath)
data$BsmtHalfBath= as.factor(data$BsmtHalfBath)
data$FullBath= as.factor(data$FullBath)
data$HalfBath= as.factor(data$HalfBath)
data$BedroomAbvGr= as.factor(data$BedroomAbvGr)
data$TotRmsAbvGrd= as.factor(data$TotRmsAbvGrd)
data$Fireplaces= as.factor(data$Fireplaces)
data$GarageCars= as.factor(data$GarageCars)
data$MoSold= as.factor(data$MoSold)
summary(data)
sapply(data, function(x) sum(is.na(x)))
boxplot(data$SalePrice)
quantile(data$SalePrice, c(0,0.05,0.1,0.25,0.5,0.75,0.90,0.95,0.97,0.98,0.985,0.99,0.995,1))
data2<-data[data$SalePrice<=416183,]
data<-data2
sapply(data, function(x) sum(is.na(x)))
data<-na.omit(data)
nrow(data)
nrow(data)