setwd("E:\\finder\\work\\R\\kaggle\\mercariPrice")
library(boot) 
library(car)
library(QuantPsyc)
library(lmtest)
library(sandwich)
library(vars)
library(nortest)
library(MASS)
test<- read.delim ("E:\\finder\\work\\R\\kaggle\\mercariPrice\\test.tsv")
train<- read.delim("E:\\finder\\work\\R\\kaggle\\mercariPrice\\train.tsv")
head(test)
str(test)
test$name<-as.character(test$name)
test$item_description<-as.integer(test$item_description)
str(train)
summary(train)
boxplot(train$price)
quantile(train$price, c(0,0.05,0.1,0.25,0.5,0.75,0.90,0.95,0.99,0.995,1))
train2<-train[train$price <=230 , ]
boxplot(train2$price)
train3<-train[train$price<=170,]
boxplot(train3$price)
nrow(train)
nrow(train2)
nrow(train3)
quantile(train3$price, c(0,0.05,0.1,0.25,0.5,0.75,0.90,0.95,0.97,0.98,0.985,0.99,0.995,1))
train<-train3
sapply(train,function(x) sum (is.na(x)))
head(train)
train$name<-as.character(train$name)
train$item_description<-as.integer(train$item_description)
train$shipping<-as.factor(train$shipping)
train$item_condition_id<-as.factor(train$item_condition_id)
nrow(train)
names(train)
fit <- lm(price ~ train_id + name + item_condition_id + category_name +  brand_name +  shipping + item_description ,data= train )

